# Generated by Django 4.1.2 on 2022-10-22 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0005_alter_matchresult_recorded_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='team_reference',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='recorded_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 20, 36, 27, 500739)),
        ),
    ]
