# Generated by Django 4.1.2 on 2022-10-21 22:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scouting_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="matchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_number", models.IntegerField(default=0)),
                ("team_number", models.IntegerField(default=0)),
                (
                    "recorded_time",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 10, 21, 17, 32, 59, 824672)
                    ),
                ),
                ("auto_ball", models.IntegerField(default=0)),
                ("auto_move", models.BooleanField(default=False)),
                ("teleop_ball", models.IntegerField(default=0)),
                ("climb_level", models.IntegerField(default=0)),
                ("climb_time", models.IntegerField(default=0)),
                ("penalty", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scouting_app.event",
                    ),
                ),
                (
                    "team_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scouting_app.team",
                    ),
                ),
            ],
        ),
    ]
