# Generated by Django 4.1.2 on 2022-10-22 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scouting_app", "0002_event_team_matchresult"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchresult",
            old_name="auto_ball",
            new_name="auto_score",
        ),
        migrations.RenameField(
            model_name="matchresult",
            old_name="climb_level",
            new_name="endgame_score",
        ),
        migrations.RenameField(
            model_name="matchresult",
            old_name="climb_time",
            new_name="endgame_time",
        ),
        migrations.RenameField(
            model_name="matchresult",
            old_name="team_number",
            new_name="teleop_score",
        ),
        migrations.RemoveField(
            model_name="matchresult",
            name="teleop_ball",
        ),
        migrations.AddField(
            model_name="matchresult",
            name="tippy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="recorded_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 21, 20, 14, 37, 428335)
            ),
        ),
    ]
