# Generated by Django 4.1.2 on 2022-10-22 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scouting_app", "0004_matchresult_team_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchresult",
            name="recorded_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 21, 20, 18, 35, 461213)
            ),
        ),
    ]
