# Generated by Django 4.1.2 on 2022-10-24 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scouting_app", "0010_rename_event_matchresult_linked_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scouting_app.event",
                    ),
                ),
                (
                    "registered_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scouting_app.team",
                    ),
                ),
            ],
        ),
    ]
