# Generated by Django 4.1.3 on 2022-12-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scouting_app", "0015_matchresult_alliance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchresult",
            name="alliance",
            field=models.CharField(max_length=4),
        ),
    ]
