# Generated by Django 4.1.7 on 2023-03-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scouting_app", "0017_remove_matchresult_auto_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="pickup_locations",
            field=models.BinaryField(verbose_name=b"\x08"),
        ),
        migrations.AlterField(
            model_name="team",
            name="scoring_locations",
            field=models.BinaryField(default=b"\x08"),
        ),
    ]
