# Generated by Django 4.1.7 on 2023-03-09 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scouting_app", "0018_alter_team_pickup_locations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="average_scoring_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 3, 9, 21, 54, 28, 823352, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
