# Generated by Django 4.1.7 on 2023-03-09 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scouting_app", "0019_alter_team_average_scoring_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="average_scoring_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 3, 9, 21, 55, 9, 395550, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
