# Generated by Django 4.1.7 on 2023-03-09 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scouting_app", "0020_alter_team_average_scoring_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="autos",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="average_scoring_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 3, 9, 22, 28, 59, 347055, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
